[package]
name = "solidity"
version = "0.1.0"
authors = ["Camden Smallwood <camden.smallwood@gmail.com>"]
edition = "2021"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
eth-lang-utils = { path = "../eth-lang-utils" }
yul = { path = "../yul" }
