[package]
name = "solidity"
version = "0.1.0"
authors = ["Camden Smallwood <camden.smallwood@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
yul = { path = "../yul" }
